### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by siddharthumakarthikeyan** [vkotaru/differential_flatness#1]
Hello,
Thanks for sharing this code. Would like to run this code in my machine and understand how it works. It would be greatly helpful if you give stepwise instruction on how to run this code in our machine. Thanks

**Comment by vkotaru** [comment]
Which version of the code are you looking for? Python and C++ versions are not well developed. For Matlab, take a look at this https://github.com/vkotaru/differential_flatness/blob/master/matlab/%2Bdiff_flat/flat2state_script.m

**Comment by siddharthumakarthikeyan** [comment]
It would be greatly helpful if you can share a explanation video on how to use this code in MATLAB
